name: 'Check'

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
    
jobs:
  check_repo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkov GitHub Action
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        
    - run: tree
    
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif

